import React from 'react';
import './Article.css';

class Article extends React.Component{
  render(){
    return(
      <div className = "article">
        <div id = "title">
          <p className = "titleText"><em>Turritopsis dohrnii</em></p>
          <hr></hr>
        </div>
        <p> From Wikipedia, the free encyclopedia </p>
        <p><b>Turritopsis dohrnii</b>, also known as the <b>immortal jellyfish</b>, is a <a className = "App-link" href = "https://en.wikipedia.org/wiki/Species" >species</a> of small, <a className = "App-link" href = "https://en.wikipedia.org/wiki/Biological_immortality">biologically immortal</a> <a className = "App-link" href = "https://en.wikipedia.org/wiki/Jellyfish">jellyfish<sup><a href = "#foot">[1]</a></sup></a> found in the Mediterranean Sea and in the waters of Japan<sup><a href = "#foot">[2][3]</a></sup>. It is one of the few known cases of <a className = "App-link" href = "https://en.wikipedia.org/wiki/Animal">animals</a> capable of reverting completely to a sexually immature, colonial stage after having reached sexual maturity as a solitary individual<sup><a href = "#foot">[4]</a></sup>. Others include the jellyfish <a className = "App-link" href = "https://en.wikipedia.org/wiki/Laodicea_undulata">Laodicea undulata</a> and species of the genus<a className = "App-link" href = "https://en.wikipedia.org/wiki/Aurelia_(cnidarian)"> Aurelia</a>.</p>
        <p>Like most other <a className = "App-link" href = "https://en.wikipedia.org/wiki/Hydrozoa">hydrozoans</a>, T. dohrnii begin their life as tiny, free-swimming <a className = "App-link" href = "https://en.wikipedia.org/wiki/Larva">larvae</a> known as <a className = "App-link" href = "https://en.wikipedia.org/wiki/Planula">planulae</a>. As a planula settles down, it gives rise to a colony of <a className = "App-link" href = "https://en.wikipedia.org/wiki/Polyp_(zoology)">polyps</a> that are attached to the sea-floor. All the polyps and jellyfish arising from a single planula are genetically identical clones. The polyps form into an extensively branched form, which is not commonly seen in most jellyfish. Jellyfish, also known as medusae, then bud off these polyps and continue their life in a free-swimming form, eventually becoming sexually mature. When sexually mature they have been known to prey on other jellyfish species at a rapid pace. If a <em>T. dohrnii jellyfish</em> is exposed to environmental stress or physical assault, or is sick or old, it can revert to the polyp stage, forming a new polyp colony. It does this through the cell development process of <a className = "App-link" href = "https://en.wikipedia.org/wiki/Transdifferentiation">transdifferentiation</a>, which alters the <a className = "App-link" href = "https://en.wikipedia.org/wiki/Cellular_differentiation">differentiated state of the cells</a> and transforms them into new types of cells.</p>
        <p>Theoretically, this process can go on indefinitely, effectively rendering the jellyfish biologically immortal, although in practice individuals can still die. In nature, most <em>Turritopsis</em> are likely to succumb to predation or disease in the medusa stage, without reverting to the polyp form.</p>
        <p>The capability of biological immortality with no maximum lifespan makes <em>T. dohrnii</em> an important target of basic biological, <a className = "App-link" href = "https://en.wikipedia.org/wiki/Ageing">aging</a> and <a className = "App-link" href = "https://en.wikipedia.org/wiki/Medication">pharmaceutical</a> research.</p>
        <p>The "immortal jellyfish" was formerly classified as <a className = "App-link" href = "https://en.wikipedia.org/wiki/Turritopsis_nutricula">T. nutricula</a>.</p>
        <nav>
          <p><strong>Contents</strong></p>
          <a className = "App-link" href = "#description">1 Description</a> <br></br>
          <a className = "App-link" href = "#invasion">2 Distribution and invasion</a> <br></br>
          <a className = "App-link" href = "#cycle">3 Life Cycle</a> <br></br>
          <a  className = "App-link" href = "#references">4 References</a>
        </nav>
        <p className = "sectionText" id = "description">Description</p>
        <hr></hr>
        <p>The medusa of <em>Turritopsis dohrnii</em> is bell-shaped, with a maximum diameter of about 4.5 millimetres (0.18 in) and is about as tall as it is wide. The mesoglea in the walls of the bell is uniformly thin, except for some thickening at the apex. The relatively large stomach is bright red and has a cruciform shape in cross section. Young specimens 1 mm in diameter have only eight tentacles evenly spaced out along the edge, whereas adult specimens have 80–90 tentacles. The medusa (jellyfish) is free-living in the plankton. Dense <a className = "App-link" href = "https://en.wikipedia.org/wiki/Nerve_net">nerve net</a> cells are also present in the <a className = "App-link" href = "https://en.wikipedia.org/wiki/Epidermis">epidermis</a> in the cap. They form a large ring-like structure above the radial canal commonly presented in cnidarians.
        </p>
        <p><em>Turritopsis dohrnii</em> also has a bottom-living polyp form, or hydroid, which consists of <a className = "App-link" href = "https://en.wikipedia.org/wiki/Stolon">stolons</a> that run along the substrate, and upright branches with feeding polyps that can produce medusa buds. These polyps develop over a few days into tiny 1 mm medusae, which are liberated and swim free from the parent hydroid colony.
        </p>
        <p>
          Images of both the medusa and polyp of the closely related species <a className = "App-link" href = "https://en.wikipedia.org/wiki/Turritopsis_rubra">Turritopsis rubra</a> from <a className = "App-link" href = "https://en.wikipedia.org/wiki/New_Zealand">New Zealand</a> can be found online. Until a recent genetic study, it was thought that <em>Turritopsis rubra</em> and <em>Turritopsis nutricula</em> were the same. It is not known whether or not <em>T. rubra</em> medusae can also transform back into polyps.
        </p>
        <p className = "sectionText" id = "invasion">Distribution and invasion</p>
        <hr></hr>
        <p><em>Turritopsis</em> is believed to have originated in the Pacific but has spread all over the world through trans-Arctic migrations, and has speciated into several populations that are easy to distinguish morphologically, but whose species distinctions have recently been verified by a study and comparison of mitochondrial ribosomal gene sequences. <em>Turritopsis</em> are found in temperate to tropical regions in all of the world's oceans. <em>Turritopsis</em> is believed to be spreading across the world through <a className = "App-link" href = "https://en.wikipedia.org/wiki/Ballast_water_discharge_and_the_environment">ballast water discharge</a>. Unlike other species invasions which caused serious economic and ecological consequences, T. dohrnii's invasion around the world was unnoticed due to their tiny size and innocuity. &quot;We are looking at a worldwide silent invasion&quot;, said <a className = "App-link" href = "https://en.wikipedia.org/wiki/Smithsonian_Tropical_Research_Institute">Smithsonian Tropical Marine Institute</a> scientist Dr. Maria Miglietta.
        </p>
        <p className = "sectionText" id = "cycle">Life cycle</p>
        <hr></hr>
        <p>The eggs develop in gonads of female medusae, which are located in the walls of the manubrium (stomach). Mature eggs are presumably spawned and fertilized in the sea by sperm produced and released by male medusae, as is the case for most hydromedusae, although the related species Turritopsis rubra seems to retain fertilized eggs until the planula stage.[16] Fertilized eggs develop into planula larvae, which settle onto the sea-floor (or even the rich marine communities that live on floating docks), and develop into polyp colonies (<a className = "App-link" href = "https://en.wikipedia.org/wiki/Hydroid_(zoology)">hydroids</a>). The hydroids bud new jellyfishes, which are released at about one millimetre in size and then grow and feed in the plankton, becoming sexually mature after a few weeks (the exact duration depends on the ocean temperature; at 20 °C (68 °F) it is 25 to 30 days and at 22 °C (72 °F) it is 18 to 22 days). Medusae of T. dohrnii are able to survive between 14 °C and 25 °C.</p>
        <p className = "boldText"><strong>Biological immortality</strong></p>
        <p>Most jellyfish species have a relatively fixed life-span, which varies by species from hours to many months (long-lived mature jellyfish spawn every day or night; the time is also fairly fixed and species-specific).[19] The medusa of Turritopsis dohrnii is the only form known to have developed the ability to return to a polyp state, by a specific transformation process that requires the presence of certain cell types (tissue from both the jellyfish bell surface and the circulatory canal system).</p>
        <p>Experiments have revealed that all stages of the medusae, from newly released to fully mature individuals, can transform back into polyps under the conditions of starvation, sudden temperature change, reduction of salinity and artificial damage of the bell with forceps or scissors. The transforming <a className = "App-link" href = "https://en.wikipedia.org/wiki/Jellyfish">medusa</a> is characterized first by deterioration of the bell, mesoglea, and tentacles. All immature medusa (with 12 tentacles at most) then turned into a <a className = "App-link" href = "https://en.wikipedia.org/wiki/Microbial_cyst">cyst</a>-like stage and then transformed into <a className = "App-link" href = "https://en.wikipedia.org/wiki/Stolon">stolons</a> and polyps. However, about 20%-40% of mature medusa went into the stolons and polyps stage without passing the cyst-like stage. Polyps were formed after 2 days since stolons had developed and fed on food. Polyps further multiply by growing additional stolons, branches and then polyps, to form colonial <a className = "App-link" href = "https://en.wikipedia.org/wiki/Hydroid_(zoology)">hydroids</a>. In the experiment, they would eventually transform into stolons and polyps and begin their lives once again even without suffering from environment changes or injury. Diagram of the transformation procedure can be found at the further reading.</p>
        <p>This ability to reverse the biotic cycle (in response to adverse conditions) is unique in the <a className = "App-link" href = "https://en.wikipedia.org/wiki/Animal">animal kingdom</a>, and allows the jellyfish to bypass death, rendering Turritopsis dohrnii potentially <a className = "App-link" href = "https://en.wikipedia.org/wiki/Biological_immortality">biologically immortal</a>. The process has not been observed in their natural habitat, in part because the process is quite rapid, and because field observations at the right moment are unlikely. Regardless, most individual medusae are likely to fall victim to the general hazards of life as <a className = "App-link" href = "https://en.wikipedia.org/wiki/Plankton#Size_groups">mesoplankton</a>, including being eaten by predators or succumbing to disease.</p>
        <div id="foot">
          <p className = "sectionText" id = "references">References</p>
          <hr></hr>
          <ul>
            <li><p>1. Schuchert P, ed. (2012). <a className = "App-link" href = "https://en.wikipedia.org/wiki/Microbial_cyst">cyst</a>-like stage and then transformed into <a className = "App-link" href = "http://www.marinespecies.org/aphia.php?p=taxdetails&id=151801">"Turritopsis dorhnii (Weissmann, 1883)"</a>. <em>World Hydrozoa database</em>. <a className = "App-link" href = "https://en.wikipedia.org/wiki/World_Register_of_Marine_Species">World Register of Marine Species</a>. Retrieved November 29, 2012.</p></li>
            <li><p>2. Bavestrello, Giorgio; Christian Sommer; Michele Sarà (1992). "Bi-directional conversion in Turritopsis nutricula (Hydrozoa)". <em>Scientia Marina</em>. 56 (2–3): 137–140.</p></li>
            <li><p>3. Koizumi, Osamu; Hamada, Shun; Minobe, Sumiko; Hamaguchi-Hamada, Kayoko; Kurumata-Shigeto, Mami; Nakamura, Masaru; Namikawa, Hiroshi (2015). "The nerve ring in cnidarians: its presence and structure in hydrozoan medusae". Zoology. 118 (2): 79–88. </p></li>
            <li><p>4.  Mihai, Andrei (December 5, 2008). <a className = "App-link" href = "https://www.zmescience.com/science/biology/meet-the-worlds-only-immortal-animal/">"Meet the world's only immortal animal"</a>. <em>ZME Science</em>. Retrieved January 10, 2015.</p></li>
          </ul>
        </div>
      </div>
    )
  }
}

export default Article;
